# Generated by Django 5.0.6 on 2024-07-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopy',
            name='password',
            field=models.CharField(default=123, max_length=25),
            preserve_default=False,
        ),
    ]
