# Generated by Django 5.0.6 on 2024-07-13 10:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_usercopy_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usercopy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='signup.usercopy')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
