# Generated by Django 5.0.6 on 2024-07-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_usercopy_deposit_usercopy_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='UPI_ID',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
