# Generated by Django 4.2.3 on 2024-07-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_deposit_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercopy',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
