# Generated by Django 4.2.3 on 2024-07-16 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0009_rename_upi_id_usercopy_upi_id_plan_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='UPI_ID',
            new_name='upi_id',
        ),
        migrations.AddField(
            model_name='deposit',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='usercopy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL),
        ),
    ]
