# Generated by Django 4.2.3 on 2024-07-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_rename_upi_id_deposit_upi_id_deposit_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='usercopy',
            new_name='user',
        ),
    ]
