# Generated by Django 4.2.3 on 2024-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_alter_deposit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
