# Generated by Django 4.2.3 on 2024-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopy',
            name='account_holder',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usercopy',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercopy',
            name='ifsc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
