# Generated by Django 4.2.3 on 2024-07-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_usercopy_account_holder_usercopy_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopy',
            name='coin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
