# Generated by Django 4.2.3 on 2024-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0017_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
