# Generated by Django 4.2.3 on 2024-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0019_alter_withdraw_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopy',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
