# Generated by Django 4.2.3 on 2024-07-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0020_usercopy_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='upi_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='upi_id',
            field=models.CharField(max_length=50),
        ),
    ]
