# Generated by Django 4.2.3 on 2024-07-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0021_alter_deposit_upi_id_alter_withdraw_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='daily',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
