# Generated by Django 4.2.3 on 2024-07-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0022_deposit_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.plan'),
        ),
    ]
