# Generated by Django 4.2.3 on 2024-07-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0024_alter_usercopy_account_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopy',
            name='invitational_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
